import express from "express";
import {Login, mcount1, mcount10, mcount11, mcount12, mcount2, mcount3, mcount4, mcount5, mcount6, mcount7, mcount8, mcount9, signout, tokentest} from "../controllers/Users.js";
import { Upload,getUsers,Del,update, change_password ,Searching , tcount , pcount ,ccount} from "../controllers/Users.js";
// import { getUsers, Register, Login, Logout, updateuser } from "../controllers/Users.js";
// import { attendee } from "../controllers/employee.js";
// import { verifyToken } from "../middleware/VerifyToken.js";
// import { refreshToken } from "../controllers/RefreshToken.js";
// import { Del } from "../controllers/Users.js";
// import { removeruser } from "../controllers/Users.js";
// import { leave } from "../controllers/leave.js";
const router = express.Router();

router.get('/users',  getUsers);
router.get('/search',Searching);
// router.post('/users', Register);
router.post('/update',update);
router.post('/login', Login);
router.post("/upload",Upload);
router.post("/removetoken",signout);
router.get('/tokencheck',tokentest);
// router.get('/token', refreshToken);
// router.delete('/logout', Logout);
router.post('/del',Del);
router.get('/total',tcount);
router.get('/complete',ccount);
router.get('/progress',pcount);
router.post('/change',change_password);
router.get('/january',mcount1);
router.get('/february',mcount2);
router.get('/march',mcount3);
router.get('/april',mcount4);
router.get('/may',mcount5);
router.get('/june',mcount6);
router.get('/july',mcount7);
router.get('/august',mcount8);
router.get('/september',mcount9);
router.get('/october',mcount10);
router.get('/november',mcount11);
router.get('/december',mcount12);
// router.post("/attendance",attendee);
// router.post("/remove",removeruser);
// router.post("/leave",leave);

export default router;